[2025-10-06T16:36:59.919+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Airflow_Lab1.load_model_task scheduled__2025-10-05T16:35:42.964584+00:00 [queued]>
[2025-10-06T16:36:59.923+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Airflow_Lab1.load_model_task scheduled__2025-10-05T16:35:42.964584+00:00 [queued]>
[2025-10-06T16:36:59.924+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-10-06T16:36:59.924+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2025-10-06T16:36:59.924+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-10-06T16:36:59.930+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): load_model_task> on 2025-10-05 16:35:42.964584+00:00
[2025-10-06T16:36:59.933+0000] {standard_task_runner.py:55} INFO - Started process 301 to run task
[2025-10-06T16:36:59.935+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Airflow_Lab1', 'load_model_task', 'scheduled__2025-10-05T16:35:42.964584+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmptolk3y1w']
[2025-10-06T16:36:59.937+0000] {standard_task_runner.py:83} INFO - Job 16: Subtask load_model_task
[2025-10-06T16:36:59.962+0000] {task_command.py:388} INFO - Running <TaskInstance: Airflow_Lab1.load_model_task scheduled__2025-10-05T16:35:42.964584+00:00 [running]> on host 92a1df9693a6
[2025-10-06T16:36:59.996+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=your_name
AIRFLOW_CTX_DAG_ID=Airflow_Lab1
AIRFLOW_CTX_TASK_ID=load_model_task
AIRFLOW_CTX_EXECUTION_DATE=2025-10-05T16:35:42.964584+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-10-05T16:35:42.964584+00:00
[2025-10-06T16:36:59.997+0000] {logging_mixin.py:137} INFO - Optimal no. of clusters: 8
[2025-10-06T16:37:00.001+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/sklearn/base.py:444: UserWarning: X has feature names, but KMeans was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"

[2025-10-06T16:37:00.030+0000] {python.py:177} INFO - Done. Returned value was: 9
[2025-10-06T16:37:00.069+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=Airflow_Lab1, task_id=load_model_task, execution_date=20251005T163542, start_date=20251006T163659, end_date=20251006T163700
[2025-10-06T16:37:00.118+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2025-10-06T16:37:00.134+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
